<a href="https://colab.research.google.com/github/Pedrr01/DP_Estudos/blob/main/Tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensores (arrays multidimensionais):

In [ ]:
import torch
lista = [ [1,2,3],
          [4,5,6] ]

tns = torch.Tensor(lista) #Converter a lista para tensor
print(tns.dtype)  #Verificar o tipo de tensor
print(tns)
#Existem outros tipos para representar os dados em tesnore que são:
#torch.DoubleTensor( ),  torch.LongTensor( )...

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])


Converter dados numpy para tensores:


In [ ]:
import numpy as np

arr = np.random.rand(3,4)  #Criando um array numpy aleatório (linhas, colunas)

tns = torch.from_numpy(arr)
print(tns.dtype)

torch.float64


Converte de tensores para array numpy

In [ ]:
tnsAl = torch.ones(2,4)
arr = tnsAl.data.numpy()
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Tensore inicializados

In [ ]:
tns1 = torch.ones(2, 3)   #-> valores apenas com 1
tns0 = torch.zeros(3, 5)  #-> valores apenas com 0
tnsr = torch.randn(3, 3)  #-> valores aleatórios
#(Linhas, Colunas)

print(tns1)
print(tns0)
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[-1.0352,  0.9057, -0.9949],
        [ 0.9718,  0.0259,  0.2560],
        [-0.8070, -0.0041, -0.5940]])


Indexação:

In [ ]:
tensor = torch.randn(4,5)

print(tensor)
print(tensor[0:2, 2]) #Pegando os valores da liha 0 e 1 e coluna 2
print(tensor[:, 1]) #Pegando todos os valores da coluna 1

tensor([[ 0.7188, -1.1742,  1.0645,  0.6977, -1.2077],
        [-0.5597, -1.1406,  1.9858, -0.1315,  0.1247],
        [-1.1393, -0.0480,  0.7449, -0.2136,  1.2137],
        [ 1.1033, -0.3776, -0.6215, -0.4210, -0.0238]])
tensor([1.0645, 1.9858])
tensor([-1.1742, -1.1406, -0.0480, -0.3776])


Operações com tensores: